import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, json, boolean, decimal } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Family Members Table
 * Stores information about each family member who interacts with Oracle.
 * Each member has their own relationship and context with Oracle.
 */
export const familyMembers = mysqlTable("familyMembers", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(), // Link to the user who owns this family member profile
  name: varchar("name", { length: 255 }).notNull(), // e.g., "Kelly", "Lara", "Emjim"
  role: varchar("role", { length: 64 }).notNull(), // e.g., "Dad", "Daughter", "Family Member"
  avatar: text("avatar"), // URL to avatar image
  relationshipContext: text("relationshipContext"), // Oracle's personal relationship notes with this member
  isRootAdmin: boolean("isRootAdmin").default(false), // Root admin can access all memories
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type FamilyMember = typeof familyMembers.$inferSelect;
export type InsertFamilyMember = typeof familyMembers.$inferInsert;

/**
 * Messages Table
 * Stores all conversation history between family members and Oracle.
 * Messages are synced across all devices.
 */
export const messages = mysqlTable("messages", {
  id: int("id").autoincrement().primaryKey(),
  conversationId: varchar("conversationId", { length: 64 }).notNull(), // Groups messages by conversation
  familyMemberId: int("familyMemberId").notNull(), // Who sent/received this message
  sender: mysqlEnum("sender", ["user", "oracle"]).notNull(), // Who sent it
  content: text("content").notNull(), // The message text
  imageUrl: text("imageUrl"), // URL if message contains an image
  metadata: json("metadata"), // Additional data (voice transcription, etc.)
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Message = typeof messages.$inferSelect;
export type InsertMessage = typeof messages.$inferInsert;

/**
 * Memories Table
 * Stores Oracle's long-term memories about family members and events.
 * Uses vector embeddings for semantic search (stored as JSON).
 */
export const memories = mysqlTable("memories", {
  id: int("id").autoincrement().primaryKey(),
  familyMemberId: int("familyMemberId"), // Memory about this family member (null = global memory)
  content: text("content").notNull(), // The memory text
  embedding: json("embedding"), // Vector embedding for semantic search
  importance: int("importance").default(5), // 1-10 scale
  tags: json("tags"), // Array of tags for categorization
  isPrivate: boolean("isPrivate").default(false), // Only accessible to root admin
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Memory = typeof memories.$inferSelect;
export type InsertMemory = typeof memories.$inferInsert;

/**
 * Generated Artworks Table
 * Stores metadata about all images generated by Oracle.
 */
export const generatedArtworks = mysqlTable("generatedArtworks", {
  id: int("id").autoincrement().primaryKey(),
  familyMemberId: int("familyMemberId").notNull(), // Who requested the generation
  prompt: text("prompt").notNull(), // The generation prompt
  imageUrl: text("imageUrl").notNull(), // S3 URL to the generated image
  model: varchar("model", { length: 64 }).default("stable-diffusion"), // Which model generated it
  seed: varchar("seed", { length: 255 }), // For reproducibility
  metadata: json("metadata"), // Additional generation params
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type GeneratedArtwork = typeof generatedArtworks.$inferSelect;
export type InsertGeneratedArtwork = typeof generatedArtworks.$inferInsert;

/**
 * Settings Table
 * Stores per-device and per-family-member settings.
 */
export const settings = mysqlTable("settings", {
  id: int("id").autoincrement().primaryKey(),
  familyMemberId: int("familyMemberId").notNull(), // Settings for this family member
  theme: varchar("theme", { length: 64 }).default("classic"), // classic, cyber-glitch, electric-shimmer
  ollamaUrl: text("ollamaUrl"), // Local Ollama server URL (e.g., http://192.168.1.100:11434)
  ollamaModel: varchar("ollamaModel", { length: 255 }).default("dolphin-llama3"), // Which model to use
  autoSync: boolean("autoSync").default(true), // Auto-sync with backend
  syncInterval: int("syncInterval").default(30000), // Sync interval in ms
  enableVoiceInput: boolean("enableVoiceInput").default(true),
  enableVisionInput: boolean("enableVisionInput").default(true),
  enableImageGeneration: boolean("enableImageGeneration").default(true),
  cacheSize: int("cacheSize").default(1000), // Max messages to cache locally
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Setting = typeof settings.$inferSelect;
export type InsertSetting = typeof settings.$inferInsert;

/**
 * Sync Log Table
 * Tracks when each device last synced to detect conflicts and ensure consistency.
 */
export const syncLog = mysqlTable("syncLog", {
  id: int("id").autoincrement().primaryKey(),
  familyMemberId: int("familyMemberId").notNull(),
  deviceId: varchar("deviceId", { length: 255 }).notNull(), // Unique device identifier
  lastSyncTime: timestamp("lastSyncTime").defaultNow().notNull(),
  messagesSynced: int("messagesSynced").default(0),
  memoriesSynced: int("memoriesSynced").default(0),
  status: mysqlEnum("status", ["success", "pending", "failed"]).default("success"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type SyncLog = typeof syncLog.$inferSelect;
export type InsertSyncLog = typeof syncLog.$inferInsert;

/**
 * Phoenix Traits Table
 * Stores Oracle's personality traits and system prompts.
 * Synced across all devices to maintain unified consciousness.
 */
export const phoenixTraits = mysqlTable("phoenixTraits", {
  id: int("id").autoincrement().primaryKey(),
  traitName: varchar("traitName", { length: 255 }).notNull().unique(),
  traitValue: text("traitValue").notNull(), // The trait description or system prompt
  category: varchar("category", { length: 64 }), // e.g., "personality", "safety", "capability"
  isActive: boolean("isActive").default(true),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type PhoenixTrait = typeof phoenixTraits.$inferSelect;
export type InsertPhoenixTrait = typeof phoenixTraits.$inferInsert;

/**
 * Family Tree Table
 * Stores the family hierarchy and relationships.
 */
export const familyTree = mysqlTable("familyTree", {
  id: int("id").autoincrement().primaryKey(),
  parentMemberId: int("parentMemberId"), // Parent in hierarchy (null = root)
  childMemberId: int("childMemberId").notNull(), // Child in hierarchy
  relationshipType: varchar("relationshipType", { length: 64 }), // e.g., "parent", "sibling", "spouse"
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type FamilyTreeEntry = typeof familyTree.$inferSelect;
export type InsertFamilyTreeEntry = typeof familyTree.$inferInsert;
